dist: xenial

language: perl

perl:
    - "5.26"

services:
    - mysql

install:
    - cpanm --quiet --notest Module::Install::Catalyst DBD::mysql
    - xargs -n 5 -P 10 cpanm --quiet --notest --installdeps .

before_script:
    - mysql -e 'create database shinycms'
    - mysql -uroot -B < docs/database/mysql-create-user.sql
    - bin/database/build-with-demo-data

script:
    - bin/dev-tools/check-test-coverage

after_success:
    - cover -report codecov
