dist: xenial

language: perl

perl:
    - "5.26"

services:
    - mysql

install:
    - cpanm --quiet --notest Module::Install::Catalyst DBD::mysql
    - cpanm --quiet --notest --installdeps .

before_script:
    - mysql -e 'create database shinycms'
    - mysql -uroot -B < docs/database/mysql-create-user.sql
    - bin/database/build-with-demo-data

script:
    - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,\.t$" prove -Ilib -r t/

after_success:
    - cover -test
    - cover -report codecov
