dist: xenial

env:
    TEST_POD=1 TEST_CRITIC=1 RECAPTCHA_OFF=1 SHINYCMS_TEST=1

language: perl

perl:
    - "5.26"

services:
    - mysql

install:
    - cpanm --quiet --notest --no-man-pages Module::Install::Catalyst Module::Build DBD::mysql
    - cpanm --quiet --notest --no-man-pages --installdeps .

before_script:
    - mysql -e 'create database shinycms_test'
    - mysql -e "create user 'shinyuser'@'%' identified by 'shinypass'"
    - mysql -e "grant all privileges on shinycms_test.* to 'shinyuser'@'%' with grant option'
    - bin/database/build-with-demo-data

script:
    - bin/test/run-tests-with-coverage

after_success:
    - cover -report codecov
