language: perl

perl:
    - "5.28"
    - "5.20"

install:
    - cpanm --quiet --notest Module::Install::Catalyst DBD::mysql
    - cpanm --quiet --notest --installdeps .

services:
    - mysql

before_script:
    - mysql -e 'create database shinycms'
    - mysql -uroot -B < docs/database/mysql-create-user.sql
    - bin/database/build-with-demo-data

script:
    - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,\.t$" prove -Ilib -r t/
    - cover -test

after_success:
    - cover -report codecov
