language: perl

perl:
    - "5.28"
    - "5.20"

install:
    - cpanm --quiet --notest Module::Install::Catalyst Module::Build DBD::mysql
    - cpanm --quiet --notest --installdeps .

services:
    - mysql

before_script:
    - mysql -e 'create database shinycms'
    - mysql -uroot -B < docs/database/mysql-create-user.sql
    - bin/database/build-with-demo-data
