dist: xenial

env:
    TEST_POD=1 TEST_CRITIC=1 RECAPTCHA_OFF=1

language: perl

perl:
    - "5.26"

services:
    - mysql

install:
    - cpanm --quiet --notest --no-man-pages \
        Module::Install::Catalyst Module::Build DBD::mysql \
        && cpanm --quiet --notest --no-man-pages --installdeps .

before_script:
    - mysql -e 'create database shinycms'
    - mysql -uroot -B < docs/database/mysql-create-user.sql
    - bin/database/build-with-demo-data

script:
    - bin/test/run-tests-with-coverage

after_success:
    - cover -report codecov
