dist: xenial

language: perl

perl:
    - "5.26"

services:
    - mysql

install:
    - cpanm --quiet --notest Module::Install::Catalyst DBD::mysql
    - cpanm --quiet --notest --installdeps .

before_script:
    - mysql -e 'create database shinycms'
    - mysql -uroot -B < docs/database/mysql-create-user.sql
    - bin/database/build-with-demo-data

env:
    - TESTDIR=t/meta t/models t/views
    - TESTDIR=t/controllers
    - TESTDIR=t/admin-controllers

script:
    - bin/dev-tools/check-test-coverage $TESTDIR

after_success:
    - cover -report codecov
