version: 2
jobs:
  build:
    docker:
    - image: perl:5
    - image: circleci/mysql:5.7
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: shinycms
        MYSQL_USER: shinyuser
        MYSQL_PASSWORD: shinypass
        MYSQL_HOSTNAME: 127.0.0.1
        TAR_OPTIONS: --no-same-owner

    steps:
    - checkout

    - restore_cache:
        key: cache-dependencies

    - run:
        name: Install distro packages
        command: |
            apt-get update && apt-get install -y \
                gcc make cpanminus libxml2 libxml2-dev libdbd-mysql-perl

    - run:
        name: Install dependencies from CPAN
        command: |
            cpanm --notest \
                Captcha::reCAPTCHA \
                Catalyst::Runtime \
                Catalyst::Action::RenderView \
                Catalyst::Plugin::ConfigLoader \
                Catalyst::Plugin::Static::Simple \
                Catalyst::Plugin::Authentication \
                Catalyst::Plugin::Session \
                Catalyst::Plugin::Session::Store::DBIC \
                Catalyst::Plugin::Session::State::Cookie \
                Catalyst::Authentication::Realm::SimpleDB Catalyst::View::TT \
                Catalyst::View::Email \
                Catalyst::TraitFor::Request::BrowserDetect \
                CatalystX::RoleApplicator \
                Config::General \
                DBIx::Class::EncodedColumn \
                DBIx::Class::Schema::Loader \
                DBIx::Class::TimeStamp \
                Email::Sender \
                Email::Valid File::Pid \
                HTML::Restrict \
                HTML::TagCloud \
                HTML::TreeBuilder \
                Method::Signatures::Simple \
                MooseX::MarkAsMethods \
                MooseX::NonMoose \
                Net::Domain::TLD \
                parent \
                Text::CSV::Simple \
                URI::Encode \
                XML::Feed

    - save_cache:
        key: cache-dependencies
        paths:
            - ~/perl5

    - run:
        name: Set up database
        command: bash bin/database/build-with-demo-data

    - run:
        name: Run tests
        command: bash bin/dev-tools/run-tests
