version: 2
jobs:
  build:
    docker:
    - image: perl:5
    - image: circleci/mysql:5.7
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: shinycms
        MYSQL_USER: shinyuser
        MYSQL_PASSWORD: shinypass
        MYSQL_HOSTNAME: 127.0.0.1
        TAR_OPTIONS: --no-same-owner
    steps:
    - checkout
    - run:
        name: Install distro packages
        command: apt-get update && apt-get install -y gcc make cpanminus libxml2 libxml2-dev libdbd-mysql-perl
    - run:
        name: Install dependencies from CPAN
        command: cpanm Catalyst::Runtime Catalyst::Plugin::ConfigLoader Catalyst::Plugin::Static::Simple Catalyst::Action::RenderView parent Config::General Catalyst::Plugin::Authentication Catalyst::Plugin::Session Catalyst::Plugin::Session::Store::DBIC Catalyst::Plugin::Session::State::Cookie Catalyst::Authentication::Realm::SimpleDB Catalyst::View::TT Catalyst::View::Email Catalyst::TraitFor::Request::BrowserDetect CatalystX::RoleApplicator DBIx::Class::EncodedColumn DBIx::Class::Schema::Loader DBIx::Class::TimeStamp Method::Signatures::Simple MooseX::NonMoose MooseX::MarkAsMethods Captcha::reCAPTCHA Email::Sender Email::Valid File::Pid HTML::Restrict HTML::TagCloud Net::Domain::TLD Text::CSV::Simple HTML::TreeBuilder URI::Encode XML::Feed DBD::mysql
    - run:
        name: Set up database
        command: bash bin/database/build-with-demo-data
    - run:
        name: Run tests
        command: bash bin/dev-tools/run-tests
